### ISSUE TITLE
Allow get/set of the flags

### ISSUE THREAD

**Issue by skx** [koron-go/z80#18]
It would be nice if it were possible to get/set the flags via named arguments.

At the moment if I want to set the Z-flag, for example, I have to know the bitfield and set that via `CPU.States.AF.Lo = 0x40`, for example.

If the flags were exposed it would be clearer what was going on.

**Comment by koron** [comment]
I implemented GetFlag, SetFlag, and ResetFlag for this purpose.
And release it as v0.10.1.

See #19 for details.
