### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by skx** [koron-go/z80#8]
I was recently looking for a Z80 emulator, written in golang, which I could use to put together a simple CP/M emulator.

I found your library via a github code search and I couldn't be more happy with it:

* The implementation seems correct.
* The sample code you have made it easy to understand how to use it.
   * Your test-code especially helped.
* The abstractions you used are at the right level.

[My cp/m emulator](https://github.com/skx/cpmulator) is 90% your work, if not more.  Thank you for sharing your code.

I copied your license, and credited you, since I'd not have written anything without this as a foundation, but it's still worth thanking you explicitly.

**Comment by koron** [comment]
Thank you too. I'm very glad to here that. I'm happy if this project was useful to you.
